# multisite + المنافذ مكشوفة على IP السيرفر
# http://IP:3000  لوحة الإدارة
# http://IP:3001  تطبيق السائق
# http://IP:3002  تطبيق الموظف
# docker compose -f docker-compose.yml -f docker-compose.override-multisite-public.yml up -d --build

services:
  app:
    ports: !override
      - "3000:3000"

  employee-web:
    ports: !override
      - "3002:3002"

  driver-web:
    ports: !override
      - "3001:3001"
